# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dzial6.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from trojkat import Ui_TrojkatWindow
from trojkatprostokatny import Ui_TrojkatProstokatnyWindow
from trojkatrownoboczny import Ui_TrojkatRownobocznyWindow
from czworokat import Ui_CzworokatWindow
from kolo import Ui_KoloWindow

class Ui_Dzial6Window(object):
    def b1Clicked(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_TrojkatWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def b2Clicked(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_TrojkatProstokatnyWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def b3Clicked(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_TrojkatRownobocznyWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def b4Clicked(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_CzworokatWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def b5Clicked(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_KoloWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, Dzial6Window):
        Dzial6Window.setObjectName("Dzial6Window")
        Dzial6Window.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Dzial6Window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 60, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 190, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.b1Clicked)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 190, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.b2Clicked)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(540, 190, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.b3Clicked)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(160, 310, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.b4Clicked)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(420, 310, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.b5Clicked)
        Dzial6Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Dzial6Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Dzial6Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Dzial6Window)
        self.statusbar.setObjectName("statusbar")
        Dzial6Window.setStatusBar(self.statusbar)

        self.retranslateUi(Dzial6Window)
        QtCore.QMetaObject.connectSlotsByName(Dzial6Window)

    def retranslateUi(self, Dzial6Window):
        _translate = QtCore.QCoreApplication.translate
        Dzial6Window.setWindowTitle(_translate("Dzial6Window", "MainWindow"))
        self.label.setText(_translate("Dzial6Window", "Planimetria"))
        self.pushButton.setText(_translate("Dzial6Window", "Trójkąt (wzory ogólne)"))
        self.pushButton_2.setText(_translate("Dzial6Window", "Trójkąt prostokątny"))
        self.pushButton_3.setText(_translate("Dzial6Window", "Trójkąt równoboczny"))
        self.pushButton_4.setText(_translate("Dzial6Window", "Czworokąty"))
        self.pushButton_5.setText(_translate("Dzial6Window", "Koła i okręgi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dzial6Window = QtWidgets.QMainWindow()
    ui = Ui_Dzial6Window()
    ui.setupUi(Dzial6Window)
    Dzial6Window.show()
    sys.exit(app.exec_())
